name: Import Secrets
# Run this workflow every time a new commit pushed to your repository
on: push
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://10.0.92.124:8200
          method: jwt
          tlsSkipVerify: true
          namespace: Tech
          role: demo
          secrets: |
            secret/data/ci app_secret | APP_SECRET
      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg app_secret="${{ env.APP_SECRET }}" -t vault-action-exampleapp
